add_newline = false

format = """$os\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$character"""

right_format = """$status\
$cmd_duration\
$jobs\
$direnv\
$conda"""

[conda]
ignore_base = false